networks:
  web:
    external: true
  backend:
    driver: bridge

services:
  backend:
    image: ${DOCKER_IMAGE_NAME}  # 또는 secrets에서 불러온 값 사용
    container_name: backend
    restart: always
    env_file:
      - backend-secret.env
    ports:
      - "8080:8080"
    volumes:
      - ./newrelic/newrelic.yml:/etc/newrelic/newrelic.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.springboot.rule=Host(`api.rexume.site`)"
      - "traefik.http.services.springboot.loadbalancer.server.port=8080"
      - "traefik.http.routers.springboot.tls=true"
      - "traefik.http.routers.springboot.tls.certresolver=letsencrypt"
    networks:
      - backend
      - web

  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
