http:
  routers:
    spring-app:
      rule: "Host(`api.rexume.site`)" && "PathPrefix(`/api/v1`)"
      entryPoints:
        - websecure
      service: spring-app
      tls:
        certResolver: letsencrypt
      middlewares:
        - rate-limit

    http-challenge:
      rule: "PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - web
      service: noop
      priority: 100


  services:
    spring-app:
      loadBalancer:
        servers:
          # Point to the backend container name and port on the Docker network
#          - url: "http://backend:8080"
          - url: "http://spring-app:8080"

  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - "${TRAEFIK_DASHBOARD_AUTH}"


    rate-limit:
      rateLimit:
        average: 50
        burst: 100
