name: CD - Deploy to Server

on:
  workflow_run:
    workflows: ["CI - Build & Push Image"]
    types:
      - completed
  workflow_dispatch:  # 👉 수동 실행용

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success')
    env:
      DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd /home/ubuntu/techeer-resume
            
            sudo mkdir -p traefik/letsencrypt
            sudo touch traefik/letsencrypt/acme.json
            sudo chmod 600 traefik/letsencrypt/acme.json
            sudo chown ubuntu:ubuntu traefik/letsencrypt/acme.json
            
            export DOCKER_USER_NAME=${{ secrets.DOCKER_USER_NAME }}
            export DOCKER_IMAGE_NAME=${{ secrets.DOCKER_IMAGE_NAME }}
            docker compose pull
            docker compose -f docker-compose.yml -f docker-compose.app.yml -f docker-compose.monitor.yml up -d