name: CD - Deploy to Server

on:
  workflow_run:
    workflows: ["CI - Build & Push Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/project-root/docker-compose
            docker compose pull
            docker compose -f docker-compose.yml -f docker-compose.app.yml -f docker-compose.monitor.yml up -d
