name: CI - Build & Push Image

on:
  push:
    paths:
      - k6/**
      - traefik/**
      - backend/**
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 (Amazon Corretto)
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'        # 올바른 배포판 이름
          java-version: '17'

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build Jar
        run: ./gradlew clean bootJar -x test

      - name: Download NewRelic Jar
        run: |
          mkdir -p newrelic
          curl -o newrelic/newrelic.jar https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic.jar
          # newrelic.yml은 resources 폴더나 별도 경로에 두었다면 복사
          cp ./src/main/resources/newrelic.yml ./newrelic/ || echo "No newrelic.yml found"

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_PW }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}-be:latest